name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Autencticar no Docker Hub
        run: echo "Executando o Docker Login"
      - name: Construção da Imagem
        run: echo "Executando o comando Docker build"
      - name: Envio da Imagem Docker
        run: echo "Executando o comando Docker push"
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Autencticar na AWS
        run: echo "Executando o comando aws config"
      - name: Configurar o kubectl
        run: echo "Executando o comando aws eks update-kubeconfig"
      - name: Deploy dos manifests no kubernetes
        run: echo "Executando o comando kubectl apply"
